# Generated by Django 5.0.7 on 2024-11-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0020_rename_branch_adbranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.IntegerField(),
        ),
    ]
